#!/bin/bash

cd /home/pi/sentinelresults    

char y = input("Would you like bluetooth results as well? y/n ")
if  y == 'y':

echo "Type scan on to continue"

sudo bluetoothctl > sentinelb

sudo iwlist wlan1 scan > sentinel0  

cat sentinelb & sentinel0

else:

sudo iwlist wlan1 scan > sentinel0

cat sentinel0

done
